### ISSUE TITLE
Support empty "accessories" array

### ISSUE THREAD

**Issue by Locutus73** [mike182uk/homebridge-zwave#12]
This seems a weird request, but, if I want to delete all HomeKit accessories created by homebridge-zwave, I think I should set "noCache" to "true" and use an empty "accessories" array. Unfortunately homebridge-zwave doesn't like this configuration, so I can delete all but one homebridge-zwave accessory. This way I have delete the accessories folder, so removing and recreating all accessories (with various problems, i.e. in Scenes).

Thank you in advance.
Regards.

**Comment by mike182uk** [comment]
Added in `2.1.0`
