### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Be2daErtin** [mike182uk/homebridge-zwave#2]
I got the installation error:

> EACCES user "nobody" does not have permission to access the dev dir

Work around was to install as below:
`sudo npm install --unsafe-perm --verbose -g homebridge-zwave`

**Comment by mike182uk** [comment]
Hey @Be2daErtin 

Thanks for reporting this. I don't think this will be something specific to this package, it's more of a general `npm` thing (if you google the error, you'll see similar errors reported on other packages). It's also probably dependant on how you have your system setup.

This may be useful though to somebody having the same problem, so thanks for reporting 👍
